[하준수] Assignment 2: Express API - 유저 회원가입 하기
wecode-bootcamp-korea/47-backend-westagram-1 pull request #8
Opened 2023-06-14 09:07 UTC by joonsooha123

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [O] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 회원가입 기능을 구현하여 DB의 user 테이블에 데이터를 입력 및 조회할 수 있다.
 

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- DB의 user 테이블에 사용자의 데이터를 추가 할 수 있는 코드 추가
- DB의 user 테이블에 기록된 사용자의 데이터를 조회할 수 있는 코드 추가

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
<img width="321" alt="image" src="https://github.com/wecode-bootcamp-korea/47-backend-westagram-1/assets/135545450/6c67b2df-9c67-4c1b-aac9-f577fd7b6d8c">

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
- DB user 테이블에 사용자 데이터 추가
![image](https://github.com/wecode-bootcamp-korea/47-backend-westagram-1/assets/135545450/b34c41ee-c657-4b22-8af7-0d2ba4fe618e)

- DB user 테이블의 사용자 데이터 조회
![image](https://github.com/wecode-bootcamp-korea/47-backend-westagram-1/assets/135545450/b9f1af63-3b11-463b-b949-a87e2a8e9ac5)

3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
- N/A

<br />

## :: 기타 질문 및 특이 사항
- n/a

2023-06-15 01:41 UTC, Kang-kyunghun requested changes

2023-06-15 01:41 UTC, Kang-kyunghun commented on joonsoo/app.js
> +  console.log(req.body);
불필요한 console.log는 제거해 주세요.
```suggestion

```

2023-06-15 06:02 UTC, kyeongraekim requested changes

2023-06-15 06:02 UTC, kyeongraekim commented on joonsoo/app.js
> +  res.json({ message: 'SUCCESS_CREATE_USER' });
- 회원가입시 전달해야 마땅한 http 상태코드를 잘 고민하여 리스폰스시 꼭 함께 전송하여주세요!
- 모든 http 통신에 대한 상태코드는 함께 동봉되어서 전송이되어야 합니다!

2023-06-15 07:45 UTC, kyeongraekim requested changes

2023-06-15 07:46 UTC, kyeongraekim requested changes

2023-06-15 07:46 UTC, kyeongraekim commented on joonsoo/app.js
> +app.get('/users', async function (req, res, next) {
- 이부분은 회원가입에 대한 기능으로서는 불필요한 코드처럼 보여지네요!
- 각 브랜치별 기능별 엄격한 코드분리는 깃 브랜치 전략에서 필수로 고려해야하는 요소입니다!

2023-06-15 10:41 UTC, kyeongraekim requested changes

2023-06-15 10:41 UTC, kyeongraekim commented on joonsoo/app.js
> +app.get('/users', async function (req, res, next) {
- 핑퐁을 찍어볼 수 있는 엔드포인트를 삭제하는 리뷰가 아니었으며, 리뷰에 대한 오해가 있어 보여 추가 코멘트 남깁니다!
- 제가 의도했던 내용은 app.get() 요청으로 유저정보를 가져오는 엔드포인트가 현재 회원가입 기능에 필요없음을 알려드리는 리뷰였습니다!

2023-06-16 02:06 UTC, joonsooha123 commented on joonsoo/app.js
> +app.get('/users', async function (req, res, next) {
네, 오해로 인해 엉뚱한 방향으로 수정한 것 같습니다.
피드백 주신 대로 핑퐁테스트 롤백 및 회원 정보 조회 코드 삭제하였습니다.

2023-06-19 06:40 UTC, kyeongraekim approved these changes

2023-06-19 06:40 UTC, merged